export const ERROR_CODES = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  REQUEST_ABORTED: 'REQUEST_ABORTED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_CODE: 'AUTH_INVALID_CODE',
  AUTH_CODE_EXPIRED: 'AUTH_CODE_EXPIRED',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_TOO_MANY_SENDS: 'AUTH_TOO_MANY_SENDS',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_CSRF_INVALID: 'AUTH_CSRF_INVALID',
  AUTH_DELIVERY_UNAVAILABLE: 'AUTH_DELIVERY_UNAVAILABLE',
  AUTH_PREAUTH_INVALID: 'AUTH_PREAUTH_INVALID',
  AUTH_REAUTH_REQUIRED: 'AUTH_REAUTH_REQUIRED',
  AUTH_IDENTITY_CONFLICT: 'AUTH_IDENTITY_CONFLICT',
  AUTH_CHANNEL_NOT_ALLOWED: 'AUTH_CHANNEL_NOT_ALLOWED',
  AUTH_CHANNEL_ALREADY_VERIFIED: 'AUTH_CHANNEL_ALREADY_VERIFIED',
  AUTH_EMAIL_VERIFICATION_REQUIRED: 'AUTH_EMAIL_VERIFICATION_REQUIRED',
  AUTH_CONTACT_UNCHANGED: 'AUTH_CONTACT_UNCHANGED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVER_ERROR: 'SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  ROUTE_ERROR: 'ROUTE_ERROR',
  CLIENT_ERROR: 'CLIENT_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

const errorCodeValues = new Set<string>(Object.values(ERROR_CODES));

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && errorCodeValues.has(value);
}
